# Generated by Django 5.2.7 on 2025-10-28 11:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='H5App',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the H5 app', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the H5 app', null=True)),
                ('app_key', models.CharField(help_text='Unique key for the H5 app', max_length=255, unique=True)),
                ('encryption_key', models.TextField(help_text='Encryption key for SuperApp integration')),
                ('notify_url', models.URLField(help_text='Callback URL for payment notifications')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the app is active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'H5 App',
                'verbose_name_plural': 'H5 Apps',
                'db_table': 'h5_apps',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_ref', models.CharField(help_text='Unique payment reference', max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10)),
                ('currency', models.CharField(default='USD', help_text='Currency code', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('ciphertext', models.TextField(blank=True, help_text='Encrypted payment data from SuperApp', null=True)),
                ('decrypted_data', models.JSONField(blank=True, help_text='Decrypted payment data', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('callback_received_at', models.DateTimeField(blank=True, help_text='When callback was received', null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('order_id', models.CharField(blank=True, help_text='External order ID', max_length=255, null=True)),
                ('h5_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.h5app')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentCallbackLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_payload', models.JSONField(help_text='Raw callback payload received')),
                ('response_sent', models.JSONField(help_text='Response sent back to SuperApp')),
                ('http_status', models.IntegerField(help_text='HTTP status code returned')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('is_successful', models.BooleanField(default=False)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callback_logs', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Payment Callback Log',
                'verbose_name_plural': 'Payment Callback Logs',
                'db_table': 'payment_callback_logs',
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_ref'], name='payments_payment_08c987_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['h5_app', 'status'], name='payments_h5_app__5e1c72_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='payments_created_e3a130_idx'),
        ),
    ]
