# Generated by Django 4.2.7 on 2025-10-31 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='app_id',
            field=models.CharField(blank=True, help_text='SuperApp App ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='callback_info',
            field=models.TextField(blank=True, help_text='Callback info from SuperApp', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='description',
            field=models.TextField(blank=True, help_text='Payment description from SuperApp', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='finish_time',
            field=models.BigIntegerField(blank=True, help_text='Finish time timestamp from SuperApp', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='mch_id',
            field=models.CharField(blank=True, help_text='Merchant ID from SuperApp', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='order_amount',
            field=models.BigIntegerField(blank=True, help_text='Order amount in smallest currency unit (cents)', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='original_order_amount',
            field=models.BigIntegerField(blank=True, help_text='Original order amount in cents (for refunds)', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='original_out_biz_id',
            field=models.CharField(blank=True, help_text='Original merchant order number (for refunds)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='original_paid_amount',
            field=models.BigIntegerField(blank=True, help_text='Original paid amount in cents (for refunds)', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='original_payment_order_id',
            field=models.CharField(blank=True, help_text='Original payment order ID (for refunds)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='original_prepay_id',
            field=models.CharField(blank=True, help_text='Original prepay ID (for refunds)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='out_biz_id',
            field=models.CharField(blank=True, help_text='Merchant order number (outBizId)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_amount',
            field=models.BigIntegerField(blank=True, help_text='Paid amount in smallest currency unit (cents)', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_order_id',
            field=models.CharField(blank=True, help_text='Payment Order ID from SuperApp', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_product',
            field=models.CharField(blank=True, help_text='Payment product (e.g., InAppH5)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='prepay_id',
            field=models.CharField(blank=True, help_text='Prepay ID from SuperApp', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='superapp_status',
            field=models.CharField(blank=True, help_text='Status from SuperApp (SUCCESS, FAILED, etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='trade_type',
            field=models.CharField(blank=True, help_text='Trade type (PAYMENT, REFUND, etc.)', max_length=50, null=True),
        ),
    ]
